/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MembersRouteImport } from './routes/members'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as EntriesRouteImport } from './routes/entries'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'
import { Route as TimerCalendarRouteImport } from './routes/timer/calendar'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSetup2faRouteImport } from './routes/auth/setup-2fa'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesRoute = EntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerCalendarRoute = TimerCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TimerRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetup2faRoute = AuthSetup2faRouteImport.update({
  id: '/auth/setup-2fa',
  path: '/auth/setup-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/entries': typeof EntriesRoute
  '/favorites': typeof FavoritesRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/shared': typeof SharedRoute
  '/tags': typeof TagsRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/timer': typeof TimerRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/setup-2fa': typeof AuthSetup2faRoute
  '/auth/signup': typeof AuthSignupRoute
  '/timer/calendar': typeof TimerCalendarRoute
  '/workspaces/new': typeof WorkspacesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/entries': typeof EntriesRoute
  '/favorites': typeof FavoritesRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/shared': typeof SharedRoute
  '/tags': typeof TagsRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/timer': typeof TimerRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/setup-2fa': typeof AuthSetup2faRoute
  '/auth/signup': typeof AuthSignupRoute
  '/timer/calendar': typeof TimerCalendarRoute
  '/workspaces/new': typeof WorkspacesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/entries': typeof EntriesRoute
  '/favorites': typeof FavoritesRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/shared': typeof SharedRoute
  '/tags': typeof TagsRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/timer': typeof TimerRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/setup-2fa': typeof AuthSetup2faRoute
  '/auth/signup': typeof AuthSignupRoute
  '/timer/calendar': typeof TimerCalendarRoute
  '/workspaces/new': typeof WorkspacesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/clients'
    | '/entries'
    | '/favorites'
    | '/members'
    | '/onboarding'
    | '/projects'
    | '/reports'
    | '/shared'
    | '/tags'
    | '/tasks'
    | '/teams'
    | '/timer'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/setup-2fa'
    | '/auth/signup'
    | '/timer/calendar'
    | '/workspaces/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/clients'
    | '/entries'
    | '/favorites'
    | '/members'
    | '/onboarding'
    | '/projects'
    | '/reports'
    | '/shared'
    | '/tags'
    | '/tasks'
    | '/teams'
    | '/timer'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/setup-2fa'
    | '/auth/signup'
    | '/timer/calendar'
    | '/workspaces/new'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/clients'
    | '/entries'
    | '/favorites'
    | '/members'
    | '/onboarding'
    | '/projects'
    | '/reports'
    | '/shared'
    | '/tags'
    | '/tasks'
    | '/teams'
    | '/timer'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/setup-2fa'
    | '/auth/signup'
    | '/timer/calendar'
    | '/workspaces/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ClientsRoute: typeof ClientsRoute
  EntriesRoute: typeof EntriesRoute
  FavoritesRoute: typeof FavoritesRoute
  MembersRoute: typeof MembersRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  SharedRoute: typeof SharedRoute
  TagsRoute: typeof TagsRoute
  TasksRoute: typeof TasksRoute
  TeamsRoute: typeof TeamsRoute
  TimerRoute: typeof TimerRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSetup2faRoute: typeof AuthSetup2faRoute
  AuthSignupRoute: typeof AuthSignupRoute
  WorkspacesNewRoute: typeof WorkspacesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries': {
      id: '/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof EntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer/calendar': {
      id: '/timer/calendar'
      path: '/calendar'
      fullPath: '/timer/calendar'
      preLoaderRoute: typeof TimerCalendarRouteImport
      parentRoute: typeof TimerRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/setup-2fa': {
      id: '/auth/setup-2fa'
      path: '/auth/setup-2fa'
      fullPath: '/auth/setup-2fa'
      preLoaderRoute: typeof AuthSetup2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TimerRouteChildren {
  TimerCalendarRoute: typeof TimerCalendarRoute
}

const TimerRouteChildren: TimerRouteChildren = {
  TimerCalendarRoute: TimerCalendarRoute,
}

const TimerRouteWithChildren = TimerRoute._addFileChildren(TimerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ClientsRoute: ClientsRoute,
  EntriesRoute: EntriesRoute,
  FavoritesRoute: FavoritesRoute,
  MembersRoute: MembersRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  SharedRoute: SharedRoute,
  TagsRoute: TagsRoute,
  TasksRoute: TasksRoute,
  TeamsRoute: TeamsRoute,
  TimerRoute: TimerRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSetup2faRoute: AuthSetup2faRoute,
  AuthSignupRoute: AuthSignupRoute,
  WorkspacesNewRoute: WorkspacesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
